"""Sector ETF mapping helpers shared across backend and models."""
from __future__ import annotations

_SECTOR_MAP: list[tuple[list[str], str]] = [
    (["NVIDIA", "INTEL", "AMD", "QUALCOMM", "BROADCOM", "APPLIED MATERIALS", "LAM RESEARCH", "MICRON", "ASML"], "SMH"),
    (["APPLE", "MICROSOFT", "ORACLE", "SALESFORCE", "SERVICENOW", "ADOBE", "CISCO", "IBM", "ACCENTURE", "PALO ALTO", "CROWDSTRIKE"], "XLK"),
    (["META", "ALPHABET", "GOOGLE", "NETFLIX", "DISNEY", "COMCAST", "CHARTER", "VERIZON", "AT&T", "T-MOBILE"], "XLC"),
    (["AMAZON", "TESLA", "HOME DEPOT", "NIKE", "MCDONALD", "STARBUCKS", "BOOKING HOLDINGS", "AIRBNB"], "XLY"),
    (["JPMORGAN", "BANK OF AMERICA", "WELLS FARGO", "CITIGROUP", "GOLDMAN SACHS", "MORGAN STANLEY", "VISA", "MASTERCARD", "AMERICAN EXPRESS", "BLACKROCK"], "XLF"),
    (["UNITEDHEALTH", "JOHNSON & JOHNSON", "ELI LILLY", "PFIZER", "ABBVIE", "MERCK", "THERMO FISHER", "AMGEN", "GILEAD", "REGENERON"], "XLV"),
    (["EXXON", "CHEVRON", "CONOCOPHILLIPS", "EOG RESOURCES", "SCHLUMBERGER", "HALLIBURTON", "OCCIDENTAL PETROLEUM", "DEVON ENERGY"], "XLE"),
    (["CATERPILLAR", "DEERE", "HONEYWELL", "GENERAL ELECTRIC", "BOEING", "LOCKHEED MARTIN", "RAYTHEON", "NORTHROP GRUMMAN"], "XLI"),
    (["NEXTERA", "DUKE ENERGY", "SOUTHERN COMPANY", "DOMINION ENERGY", "AMERICAN ELECTRIC POWER", "XCEL ENERGY"], "XLU"),
    (["FREEPORT", "NUCOR", "STEEL DYNAMICS", "AIR PRODUCTS", "LINDE", "CORTEVA", "MOSAIC", "INTERNATIONAL PAPER"], "XLB"),
    (["PROLOGIS", "AMERICAN TOWER", "CROWN CASTLE", "DIGITAL REALTY", "EQUINIX", "SIMON PROPERTY", "REALTY INCOME", "WELLTOWER"], "XLRE"),
    (["PROCTER & GAMBLE", "COCA-COLA", "WALMART", "COSTCO", "PEPSICO", "PHILIP MORRIS", "MONDELEZ", "KRAFT HEINZ"], "XLP"),
]


def name_to_sector(name: str) -> str:
    upper = str(name or "").upper()
    for keywords, etf in _SECTOR_MAP:
        if any(k in upper for k in keywords):
            return etf
    return "Other"
